### ISSUE TITLE
Finalizing Shift Documentation "Getting Started" Section

### ISSUE THREAD

**Issue by albertochimentiinbibo** [Inbibo/shift_docs#4]
Description:
The shift Documentation is currently a template.
We need to populate the index structure and content.

Current Getting Started Section:
- [x] Shift UI Overview (Breakdown of the shelf buttons for example)
- [x] Shift Terminology 
- [x] Graph Authoring
- [x] Workflow Execution
- [x] Workflow Prototyping (scriptable nodes)
- [x] Nested Workflows

After reviewing the content above, it would be great if everyone could answer to the following questions to plan what has to be done/modified.

Questions:

- [ ] Should we add any additional sections within the Getting Started Section to the above?
- [ ] Do we want to add the button icons to the public repository to source them in the Executing your Workflow section?
- [ ] Shift Terminology (do we need more? Maybe Catalog?)
- [ ] Board controls action name for multi selection with click and drag
- [ ] Review Live Execution gif
- [ ] Prototype your Workflow section is the screenshot ok? Do we want a more comprehensive one?
- [ ] Should we add an example gif which imports modules inside a PythonScript?
- [ ] Should we add sections for iterator / condition equals explanation in the Getting Started section?
- [ ] Review the structure of the index (feedback)

Additional Questions / Topics For Review:

- [ ] Review System Requirements
- [ ] Review FAQ
- [ ] Discuss release notes structure.

Definition Of Done:
When at least 3 people approve of the Content section after discussing the above questions & implementing them.

**Comment by mromeoinbibo** [comment]
Alberto, what is the best way to see a preview of this?

**Comment by albertochimentiinbibo** [comment]
> Alberto, what is the best way to see a preview of this?

The link to the mkdocs build is in the PR comment.

Reporting the link here as well: https://drive.google.com/file/d/1tj4GETzKlOuuW_Q42JDjkkhJufJW1db7/view?usp=sharing

To browse unzip the folder and double-click on the index.html file

@mromeoinbibo

**Comment by juliavisserinbibo** [comment]
### Questions
- **Should we add any additional sections within the Getting Started Section to the above?**
I wouldn't add anything else. I think the Getting Started should be the most basic overview of Shift. I would actually remove "Prototype your Workflow" and "Nested Workflows". Instead, I would create a new section for all the special functionalities (Nested workflows, python nodes, iterators, conditionals, debugging in Shift...)

- **Do we want to add the button icons to the public repository to source them in the Executing your Workflow section?**
I think it helps to better identify the icon. We can use a low-quality version of the icon in the documentation, maybe? 

-  **Shift Terminology (do we need more? Maybe Catalog?)**
Yes, I think Catalog is an important term. In the section for the Operator, it says that node and operator will be used interchangeably. I think we have to decide if we really want to use it interchangeably since the node is the graphic representation of the operator. 

-  **Board controls action name for multi selection with click and drag**
Why not just "drag selection"?

-  **Review Live Execution gif**
I think is simple and understandable.

-  **Prototype your Workflow section is the screenshot ok? Do we want a more comprehensive one?**
I think in general we should expand this section. We should also explain the output and how to add additional arguments.  The screenshot is ok, but I would rather see a gif with the result of the execution. 

-  Should we add an example gif which imports modules inside a PythonScript?
As I said before, I think we should extend a bit the whole section. We can add that information when we do that.

-  Should we add sections for iterator / condition equals explanation in the Getting Started section?
No, I think the Getting Started should be the simplest way of using shift. 

-  Review the structure of the index (feedback)
As said before, I would remove  "Prototype your Workflow" and "Nested Workflows" from Getting Started.  Maybe add a "Features" section or similar where this can go.
Then, I think that the "Installation" is part of the Getting Started section. I'm checking other software and it's most of the time is in that section (or right before/after). 
I would do:
Getting Started
-> Introduction
-> Installation
    --> Requirements
    --> Installation
    --> Licensing
-> First steps (or another name)
     --> Terminology
     --> UI 
    --> Workflow Authoring
    --> Workflow Execution

**Comment by JorgeHernandezibanezinbibo** [comment]
### **Questions:**

-  **Should we add any additional sections within the Getting Started Section to the above?**: I think we should refactor the Nesting Workflows and Prototype Your Workflow. The seccions could be merge in a other. The Python Script operator I think it's esencial, but maybe we can show more things before going into tell the user to implement something in python. For example, a explanation about catalogs, or the catalog manager could be set before the python script maybe.
-  **Do we want to add the button icons to the public repository to source them in the Executing your Workflow section?**: I think we must, it would be more easy to understand for the user.
-  **Shift Terminology (do we need more? Maybe Catalog?)**: Yes we can add a basic secction of terms. I would add Catalog, Workflow, Plug, Operator==Node, ...
-  **Board controls action name for multi selection with click and drag**: I'm not sure about this. I don't know how many drag options do we have.
-  **Review Live Execution gif**: I think it's correct.
-  **Prototype your Workflow section is the screenshot ok? Do we want a more comprehensive one?**
-  **Should we add an example gif which imports modules inside a PythonScript?**
-  **Should we add sections for iterator / condition equals explanation in the Getting Started section?**
-  **Review the structure of the index (feedback)**

### **Additional Questions / Topics For Review:**

-  Review System Requirements
-  Review FAQ
-  Discuss release notes structure.

**Comment by craigskerryinbibo** [comment]
Questions

Some small comments from me on the topics I can write about!

**Should we add any additional sections within the Getting Started Section to the above?**
We can add a small addition to the Introduction:

If you need more information or help, please do not hesitate to send an email to shiftsupport@inbibo.co.uk.

**Do we want to add the button icons to the public repository to source them in the Executing your Workflow section?**
FYI the shift buttons & UI design is being updated again (sorry that your screenshots & gifs will need to be updated!!)
In the section you have here, I would potentially change the layout so that each individual icon is placed before each lined that describes it.

![Image](https://github.com/Inbibo/shift_docs/assets/146827963/3fae6dc6-bb28-4cf9-8244-d1e2839c0f12)

**Shift Terminology (do we need more? Maybe Catalog?)**
Yeah Catalog sounds like a good addition!
