### ISSUE TITLE
Review Webpage 2

### ISSUE THREAD

**Issue by juliavisserinbibo** [Inbibo/shift_docs#76]
This issue lists all the small changes found by the team that have to be made to the website before the release of version 1.

This includes typos, broken links, image updates, reordering, or small missing pieces of information.

If any bugs are found with the webpage, please report them here:
https://docs.google.com/document/d/1TA7-F9Q4-ayznjKou3nAnWrGDQngVm3zU6LskI_x0C8/edit?usp=sharing

## NOTE
Files should be previewed from the last commit done to the `v1.0.0` branch:
https://github.com/Inbibo/shift_docs/blob/2b0c29ce77aea502ee41e527826dfa0ee026ce61/docs/index.md

**Comment by JorgeHernandezibanezinbibo** [comment]
Some updates are required. List of Issues or things to update by documentation page:

- **Requeriments**:
  - [ ] Update free space minimum from 500MB to 1.5GBs.
  - [ ] Remove Linux SO, and say that Linux support is comming soon.

**Comment by leegeertseninbibo** [comment]
![Screenshot 2024-09-12 133644](https://github.com/user-attachments/assets/e12593c4-78ae-404c-b79d-df9e5f2519d5)
This sounds a bit weird to me, as if you can use Shift forever when you have no internet connection

**Comment by hectorjimenezinbibo** [comment]
In the Reference > Nodes > Iteration nodes:
We still mention that the type of the input and output plugs are objects, but since this [PR](https://github.com/Inbibo/shift/pull/1149) are now instance plugs:
![image](https://github.com/user-attachments/assets/d1326eb8-2eea-4fef-a71e-3cc3ad9648c4)

**Comment by albertochimentiinbibo** [comment]
- In the Shift Installation page should we mention anything about the fact that that shift.bat is not signed? Users will see their windows popup a warning about untrusted software.
- In the requirements page change PyOpenGL with uppercase L. Would be amazing to also provide links to the Pypi pages for each module
- In the requirements page we are mentioning Linus in the minimum reqs. It should be removed for now.
- In the requirements we mention USD as a dependency for batch execution, however it is not true as it is needed only if you want to use pxr in the workflow. Currently the shift_batch commands do not source that. Do we want to leave it as is? Do we want to remove the distinction?
- Missing FAQ
- Text in the gifs for USD plugins is very small. We should not record at screen full size if we have a 4k monitor. At least highering the windows scaling should be done.

**Comment by mromeoinbibo** [comment]
@JorgeHernandezibanezinbibo 
- Update minimum free space from 500MB to 1.5GB. **YES**
- Remove Linux SO, and say that Linux support is comming soon. **YES**
- Should we add a section to explain how to add Shift to the Maya Shelf? **NOT NOW CAN DO AFTER V1**
- In my opinion the code to execute should be similar to this... **NO BUT WE NEED TO CHANGE IT ... WILL INFORM ON HOW TO CHANGE IT**

@leegeertseninbibo 
- On getting started/licensing... **YES WRITE THIS ISNTEAD** : `In order to start your 30 days trial period, the computer running Shift will need to be connected to the internet.`
- On getting started/basics/UI overiew... For more details, please refer to the Plugins page **NOT NECESSARY**
- On getting started/basics/UI overiew... but not for the nodes list. **YES**
- On getting started/basics/workflow authoring... **YES**
- On reference/nodes: I would change the i/o's plugs to the input and output plugs **YES**
- On reference/nodes:I would change Defines a dictionary value. **YES, CHANGE IT TO** `Defines the content of the dictionary.`
- On reference/nodes/iteration nodes: We should change the image of the Iterator node **YES**
- On reference/developer guide/developing plugins... We should also add allowMultiple: false **YES**
- On reference/developer guide/developing plugins... I would put this in a code block **NOT NECESSARY**
- On reference/developer guide/shift python api... **YES**

@hectorjimenezinbibo 
- In the Reference > Nodes > Iteration nodes page... **YES**
- In the Reference > Catalog page... **YES**

@juliavisserinbibo 
- I would add headings for the plugins in the Plugins page **YES**
- I would change it to SHIFT_PROCESS_[Interpreter Name] in the Enviorment Variable page. **YES**
- Integrations and resources make no mention of this functionality of Shift. We should remove the link to it on the Developing Catalogs page. **YES AND CREATE AN ISSUE TO BE WORKED ON AFTER V1 IS OUT TO ADD IT TO THE DEVELOPING CATALOGS DOCUMENTATION**
-  I would make a note in the documentation for Developing Catalogs about the fact that the operator's docstrings are used as the operator description. **YES**
- Do we want to list which catalogs are compatible with some DCCs? **NO, AT LEAST NOT YET**
- We need to add a space in between both paths in the Resolve page. **YES, BUT I THINK MORE OF A SPACE YOU MEANT NEW LINE**
- I believe we can remove the windows example in the Resolve Page, as we are already mentioning the path above. **NO**
- We need to make sure that the Shift_Resolve catalog is public before the release of v1. **YES, DONE**
- We have to define the Release Notes section. **YES, LOOK FOR REFERENCES OF FIRST VERSION RELEASE NOTES**
- We have to define the FAQ section. **YES, MARCO WILL CREATE A SET OF BASIC FAQS**

@albertochimentiinbibo 
- In the Shift Installation page should we mention anything about the fact that that shift.bat is not signed? **NO THIS IS UNFORTUNATELY SOMETHING COMMON ENOUGH THAT SHOULD NOT BE AN ISSUE**
- In the requirements page change PyOpenGL with uppercase L **YES**
- Would be amazing to also provide links to the Pypi pages for each module **YES, BUT AFTER V1**
- In the requirements page we are mentioning Linus in the minimum reqs. It should be removed for now. **YES**
- In the requirements we mention USD as a dependency for batch execution **REMOVE THIS FROM THAT PART OF THE DOCUMENTATION. AFTER v1 WE INTRODUCE THIS CONCEPT INTO THE SHIFT USD PART OF THE DOCUMENTATION**
- Missing FAQ **YES, MARCO WILL CREATE A SET OF BASIC FAQS**
- Text in the gifs for USD plugins is very small. We should not record at screen full size if we have a 4k monitor. At least highering the windows scaling should be done. **WILL REVIEW AFTER V1**
